### ISSUE TITLE
Translate CoC into Spanish

### ISSUE THREAD

**Issue by sanscontext** [docker/code-of-conduct#13]
We would like to provide a translation of our Code of Conduct into Spanish. If you're interested in working on this, please assign yourself and use this issue for coordination.

Please name the markdown file with `ES` at the end. :)

**Comment by Carlaplzgnz** [comment]
I'm on it! 👍

**Comment by sanscontext** [comment]
Good gracious, this has been fixed since 2016! Closing out!
