### ISSUE TITLE
Translate CoC into Japanese

### ISSUE THREAD

**Issue by sanscontext** [docker/code-of-conduct#15]
We would like to provide a translation of our Code of Conduct into Japanese. If you're interested in working on this, please assign yourself and use this issue for coordination.

Please name the markdown file with `JA` at the end. :)

**Comment by chikaando** [comment]
Food for thoughts. adding some references of other companies's CoC translation. Please add more. some are ok, some of these are terrible. 
https://www.ubuntulinux.jp/community/conduct
http://www1.jp.dell.com/content/topics/segtopic.aspx/commitment/conduct?c=jp&l=ja&s=corp
https://pycon.jp/2016/ja/about/code-of-conduct/

Github:
https://gist.github.com/atsushieno/b6fa985354b5583f027d10618f6d1438
http://atsushieno.hatenablog.com/entry/2016/11/29/234448

https://jp.linux.com/linux-community/blog/236-mirainoitsuka/420060

**Comment by RobbKistler** [comment]
closed by #28
