### ISSUE TITLE
Translate CoC into Chinese (simplified)

### ISSUE THREAD

**Issue by sanscontext** [docker/code-of-conduct#16]
We would like to provide a translation of our Code of Conduct in Simplified Chinese. If you're interested in working on this, please assign yourself and use this issue for coordination.

Please name the markdown file with `ZH-Simp` at the end. :)

**Comment by 10000TB** [comment]
Hi,
  I already added a simplified version of Docker code-of-conduct and made an pull request. feel free to leave any comment!

David

**Comment by 10000TB** [comment]
@here @sanscontext

**Comment by 10000TB** [comment]
@sanscontext, since simplified Chinese version translation has been merged, this issue probably should be closed to avoid confusion.

David

**Comment by sanscontext** [comment]
I was just checking the email for this account - @10000TB thanks, and I'll close this. @thaJeztah you probably want to remove me as a maintainer please. :)

**Comment by thaJeztah** [comment]
@sanscontext oh, yes sure (although you're always welcome here!)
