### ISSUE TITLE
Generic?

### ISSUE THREAD

**Issue by tianon** [docker/code-of-conduct#34]
Hi! :wave: 

It appears this was originally intended as a generic CoC for all Docker and Docker-related community projects and events (both online and in-person), but it seems to have become specific to DockerCon (dockercon@docker.com, etc).

Was that an intentional shift, or should this be "generified" for use in Docker open source projects again?

**Comment by tianon** [comment]
It could also end up making sense to have a "split" CoC (because I imagine there are concerns that are specific to online spaces that don't necessarily apply to in-person, and vice-versa).

Maybe worth considering something "standard" like [the Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct/) for online / open source?

**Comment by sanscontext** [comment]
@thaJeztah I think this was also used for Docker Meetup groups, wasn't it?
